In [1]:
import numpy as np


In [ ]:
#it is numerical things in python

In [2]:
l=[1,2,3,4,"sudh"]

In [3]:
type(l)

list

In [5]:
#Convert List to Array
np.array(l)

array(['1', '2', '3', '4', 'sudh'], dtype='<U11')

In [6]:
type(np.array(l))

numpy.ndarray

In [7]:
#it create N dimenstion array


In [8]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [9]:
#create array with n dimension you need to pass ndmin=4 value
np.array([[1,2,3,4]],ndmin=4)

array([[[[1, 2, 3, 4]]]])

In [10]:
#numpy matrix function
np.mat([1,2,3])

matrix([[1, 2, 3]])

In [11]:
arr=np.array([3,4,5,6,7])

In [12]:
arr

array([3, 4, 5, 6, 7])

In [13]:
arr[0]

3

In [16]:
arr[0:3]

array([3, 4, 5])

In [17]:
#get 0 to 3 with alternate  value
arr[0:3:2]

array([3, 5])

In [20]:
#create numpy create list inside list  is call 2 dimenstionla array
np.array([[1,2],[3,4]])


array([[1, 2],
       [3, 4]])

In [21]:
twodarray=np.array([[1,2],[3,4]])

In [22]:
twodarray[0:1]

array([[1, 2]])

In [23]:
twodarray[0:1][2:0]

array([], shape=(0, 2), dtype=int32)

In [24]:
twodarray[1]

array([3, 4])

In [27]:
#access value from 2d array
#array[rowID][columnID]
twodarray[1][0]

3

In [31]:
arr=np.array([[1,2],[3,4],[4,5]])

In [32]:
arr

array([[1, 2],
       [3, 4],
       [4, 5]])

In [33]:
arr[2][1]

5

In [34]:
#asarray
arr=np.asarray([1,3,4,5])

In [35]:
arr

array([1, 3, 4, 5])

In [36]:
#intger to float

arr=np.asarray([1,3,4,5],dtype=np.float32)

In [37]:
arr

array([1., 3., 4., 5.], dtype=float32)

In [38]:
#asanyarray function
np.asanyarray([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [39]:
#list into matrix
np.asanyarray(np.matrix([1,2,3,4,5,6]))

matrix([[1, 2, 3, 4, 5, 6]])

In [40]:
# if data type is not in array then it will convert into array
#but if it is already converted into any form of array then it willnot be convert n
#into array such as matrix to array


In [41]:
#fromfunction 
#basicall numpy use to convert into array and matrix

np.fromfunction(lambda i,j:i*j,(3,3),dtype=int)


array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [43]:
np.fromfunction(lambda i,j:i+j,(4,3),dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [48]:
arr=np.fromfunction(lambda i,j,k:i+j,(3,3,2),dtype=int)

In [49]:
#now acess data from array
arr

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[1, 1],
        [2, 2],
        [3, 3]],

       [[2, 2],
        [3, 3],
        [4, 4]]])

In [50]:
arr[0,1]

array([1, 1])

In [51]:
#numpy fromiter() function


In [52]:
for i in 5 :
    print(i)

TypeError: 'int' object is not iterable

In [54]:
for i in "sudh":
    print(i)

s
u
d
h


In [57]:
for i in "s":
    pass

In [58]:
for i in [1,2,3,4]:
    pass

In [60]:
s="sudh"
next(s)

TypeError: 'str' object is not an iterator

In [61]:
#"str' object is not an iterator"


In [62]:
l=[1,2,3,4,5,6]
next(l)

TypeError: 'list' object is not an iterator

In [63]:
r=range(0,4)
next(r)

TypeError: 'range' object is not an iterator

In [64]:
s="sudh"


In [65]:
i=iter(s)
next(i)

's'

In [66]:
next(i)

'u'

In [67]:
next(i)

'd'

In [68]:
next(i)

'h'

In [69]:
next(i)

StopIteration: 

In [70]:
#string is not iterator but it is itreable  to itereate value from 
#string we convert iterable to interator using next function



In [72]:
np.fromiter([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [73]:
#we pass iterable object in fromiter and datatype


In [76]:
np.fromstring("sas as ",sep=" ")

<ipython-input-76-e38f090cdea0>:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("sas as ",sep=" ")


array([], dtype=float64)

In [77]:
np.fromstring("123 as ",sep=" ")

<ipython-input-77-7fc4b93e9612>:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("123 as ",sep=" ")


array([123.])

In [78]:
l=[3,4,5,6,7,8,8]

In [80]:
arr=np.array(l)

In [81]:
arr.ndim

1

In [82]:
arr.size

7

In [84]:
arr.shape

(7,)

In [86]:
l=list(range(0,8))

In [87]:
list(range(0,8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [91]:
np.arange(0,4.6,.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5])

In [94]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [95]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [96]:
np.linspace(1,5,100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [97]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [99]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [103]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [104]:
np.ones((4,5))+1

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [105]:
np.empty(4)

array([1., 2., 3., 4.])

In [107]:
np.empty((3,5))

array([[0.3, 0.6, 0.9, 1.2, 1.5],
       [1.8, 2.1, 2.4, 2.7, 3. ],
       [3.3, 3.6, 3.9, 4.2, 4.5]])

In [111]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [112]:
np.eye(5)+2

array([[3., 2., 2., 2., 2.],
       [2., 3., 2., 2., 2.],
       [2., 2., 3., 2., 2.],
       [2., 2., 2., 3., 2.],
       [2., 2., 2., 2., 3.]])

In [113]:
np.random.rand(3,5)

array([[0.36965739, 0.68983207, 0.65959899, 0.47706395, 0.57545208],
       [0.66953701, 0.89404203, 0.51547872, 0.19462779, 0.61106752],
       [0.15399284, 0.34279622, 0.86375291, 0.24384292, 0.54871119]])

In [114]:
np.random.rand(3,5,5)

array([[[0.82480694, 0.2291345 , 0.84363667, 0.31506936, 0.87243303],
        [0.55037975, 0.81436152, 0.44067679, 0.50613285, 0.48994986],
        [0.36738399, 0.14897739, 0.85728778, 0.51659729, 0.46885862],
        [0.9952868 , 0.39032598, 0.05861183, 0.97592887, 0.89136925],
        [0.40346973, 0.1166061 , 0.2015668 , 0.24949966, 0.75808824]],

       [[0.19092948, 0.40629665, 0.99833811, 0.19034954, 0.38822018],
        [0.42168145, 0.98467398, 0.33174765, 0.66456788, 0.97400413],
        [0.67814394, 0.89099413, 0.27546552, 0.95303779, 0.92290782],
        [0.70337361, 0.30026324, 0.13139222, 0.69775785, 0.10036271],
        [0.52821861, 0.30411705, 0.55664004, 0.56669185, 0.93986965]],

       [[0.11022539, 0.20371398, 0.25744981, 0.2668322 , 0.32285436],
        [0.70311189, 0.92265457, 0.52462675, 0.71995666, 0.63823168],
        [0.50836747, 0.12197462, 0.03138256, 0.72231455, 0.03513247],
        [0.9332321 , 0.15441051, 0.6133206 , 0.85234232, 0.67336416],
        [0.88852

In [115]:
#generate 1 lac record and test performance 
np.random.rand(100000,5)

array([[0.27168923, 0.42002378, 0.883763  , 0.03156885, 0.53357618],
       [0.53739229, 0.82477635, 0.61695891, 0.52150684, 0.20974512],
       [0.01394457, 0.6411323 , 0.85527446, 0.74859747, 0.4374468 ],
       ...,
       [0.11340287, 0.7457867 , 0.18006959, 0.14925413, 0.23835146],
       [0.65122082, 0.64595868, 0.51573748, 0.26769658, 0.14681455],
       [0.77107468, 0.17292825, 0.53578132, 0.39880178, 0.6351304 ]])

In [116]:
np.random.randn(4,5)

array([[ 0.47488903,  1.63906282,  0.31436429, -1.99131377,  1.30468155],
       [ 0.25678261,  0.73778471, -1.81945324, -0.86955416,  0.30345512],
       [ 2.72042964,  0.4495563 ,  1.57819951, -0.30827356, -0.68969726],
       [-1.19659294, -0.02547841, -0.89344527, -1.54689184, -2.15207561]])

In [117]:
np.random.randint(3,4)

3

In [119]:
np.random.randint(3,40,size=60)

array([21, 19, 19, 19, 13, 12, 24, 32, 33,  7, 23, 25, 28, 30,  9,  5,  3,
       17,  9, 24, 26, 18, 15,  6, 28, 10, 11, 36,  3, 14, 14, 13, 20, 13,
       34, 15, 23,  6, 19, 24, 35, 19, 32,  6, 10, 19,  6, 21, 15, 18, 13,
       25, 26,  7, 36, 23, 18,  7,  7, 28])

In [122]:
arr=np.random.randint(3,40,(4,5))

In [123]:
arr.shape

(4, 5)

In [124]:
arr

array([[ 7,  5, 29, 13,  4],
       [36, 34, 24, 14, 31],
       [ 3,  5, 12,  4,  7],
       [24,  7, 23,  9, 28]])

In [128]:
arr.reshape(1,4,5)

array([[[ 7,  5, 29, 13,  4],
        [36, 34, 24, 14, 31],
        [ 3,  5, 12,  4,  7],
        [24,  7, 23,  9, 28]]])

In [127]:
arr.reshape(10,2)

array([[ 7,  5],
       [29, 13],
       [ 4, 36],
       [34, 24],
       [14, 31],
       [ 3,  5],
       [12,  4],
       [ 7, 24],
       [ 7, 23],
       [ 9, 28]])

In [130]:
arr.max()

36

In [131]:
arr.min()

3

In [132]:
arr[0,1]=7

In [133]:
arr

array([[ 7,  7, 29, 13,  4],
       [36, 34, 24, 14, 31],
       [ 3,  5, 12,  4,  7],
       [24,  7, 23,  9, 28]])

In [134]:
arr[0,1]=1212

In [135]:
arr

array([[   7, 1212,   29,   13,    4],
       [  36,   34,   24,   14,   31],
       [   3,    5,   12,    4,    7],
       [  24,    7,   23,    9,   28]])

In [143]:
mat1=np.random.randint(1,4,(3,3))

In [144]:
mat2=np.random.randint(1,4,(3,3))

In [146]:
mat1

array([[1, 1, 1],
       [1, 3, 2],
       [3, 2, 3]])

In [147]:
mat2

array([[1, 1, 3],
       [2, 1, 2],
       [3, 2, 2]])

In [145]:
#element wise multiplicatioon
mat1*mat2

array([[1, 1, 3],
       [2, 3, 4],
       [9, 4, 6]])

In [148]:
#Matix multiplication row X Column =row 1

In [149]:
mat1@mat2 #matrix multiplication not element multiplicatio

array([[ 6,  4,  7],
       [13,  8, 13],
       [16, 11, 19]])

In [150]:
arr

array([[   7, 1212,   29,   13,    4],
       [  36,   34,   24,   14,   31],
       [   3,    5,   12,    4,    7],
       [  24,    7,   23,    9,   28]])

In [151]:
arr[0]

array([   7, 1212,   29,   13,    4])

In [152]:
arr/0

<ipython-input-152-39e2cbdaf753>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [153]:
arr.T

array([[   7,   36,    3,   24],
       [1212,   34,    5,    7],
       [  29,   24,   12,   23],
       [  13,   14,    4,    9],
       [   4,   31,    7,   28]])

In [154]:
arr**2 #power of all element 

array([[     49, 1468944,     841,     169,      16],
       [   1296,    1156,     576,     196,     961],
       [      9,      25,     144,      16,      49],
       [    576,      49,     529,      81,     784]], dtype=int32)

In [156]:
np.log10(arr)

array([[0.84509804, 3.08350262, 1.462398  , 1.11394335, 0.60205999],
       [1.5563025 , 1.53147892, 1.38021124, 1.14612804, 1.49136169],
       [0.47712125, 0.69897   , 1.07918125, 0.60205999, 0.84509804],
       [1.38021124, 0.84509804, 1.36172784, 0.95424251, 1.44715803]])

In [157]:
np.sqrt(arr)#Sqr root

array([[ 2.64575131, 34.81379037,  5.38516481,  3.60555128,  2.        ],
       [ 6.        ,  5.83095189,  4.89897949,  3.74165739,  5.56776436],
       [ 1.73205081,  2.23606798,  3.46410162,  2.        ,  2.64575131],
       [ 4.89897949,  2.64575131,  4.79583152,  3.        ,  5.29150262]])

In [158]:
np.pi

3.141592653589793